### ISSUE TITLE
Ask for project overview

### ISSUE THREAD

**Issue by sogreatandpowerfull** [tcpstorms/sondar#2]
Some of the **questions** I have about the project:

i. What is the purpose of the nRAT project?
ii. What is it supposed to do?
iii. What is it used for?
iv. What are the long-term goals of the project?
v. How does it supposed to work?
vi. Why is it being written on go-lang?
vii. What is nRAT stand for? Is this a short form?

**Assumptions** I have made about the project based on the code or project name:

It appears that the project is a simple port scanner that allows the user to enter a host and port number and check whether the port is open or closed. It's not clear from the code or the project name what the overall purpose or goal of the project is.

**Comment by sogo747** [comment]
Hey @sogreatandpowerfull, thanks for taking the time to write this issue.
As of now, this project is nowhere near to what it is intended to be and I'm fairly new to the Go programming language and networking, which is one of the main reasons why I started this project so I can better understand networks and how they work. That being said, I'll try my best to answer the questions and give you a basic overview of the project in a paragraph format:

Currently, it's just a simple port scanner just like you've assumed, but nRAT is NOT intended to be a port scanner primarily. nRAT is supposed to be a Remote Administration Tool that will be able to run on a target computer and with that, be able to remotely manage that computer from another computer (or multiple computers in real-time, *if* given the access by an already connected computer) and also be able to read and write data across both TCP and UDP connections. nRAT may be used for personal purposes, for penetration testing or by tech support. The '*RAT*' in nRAT stands for 'Remote Administration Tool' and *'n'* being the 'network'. However, I don't quite like this name and will most probably rename it, so feel free to suggest a suited name.

Let me know if you have any other questions or suggestions. Thanks!
